AWSTemplateFormatVersion: 2010-09-09
Description: Spoiler free resources
Resources:

  Table:
    Type: "AWS::DynamoDB::Table"
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
      - AttributeName: value
        AttributeType: S
      KeySchema:
      - AttributeName: value
        KeyType: HASH # THIS IS SO IMPORTANT IT MUST BE SHOUTED

  User:
    Type: "AWS::IAM::User"
    Properties:
      Policies:
      - PolicyName: allow-dynamo
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            Resource:
             Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Table}
